export interface PlayerInfo {
    player_steam_id?: string,
    player_name?: string,
    player_side?: string,
    map_id?: number,
    match_id?: string,
    team_id?: number,
    round_number: number,
    round_time: number,
    attacker_steam_id: string,
    attacker_name: string,
    attacker_side: string,
    weapon: string,
    bomb: string,
    deaths: number,
    headshot: boolean,
    thru_smoke: boolean,
    attacker_blind: boolean,
    no_scope: boolean,
    suicide: boolean,
    friendly_fire: boolean,
    assister_steam_id: string,
    assister_name: string,
    assister_side: string,
    assist_friendly_fire: boolean,
    flash_assist: boolean
}
